### ISSUE TITLE
What about other `QwikIntrinsicElements -> ...Attributes` mappings? In or not?

### ISSUE THREAD

**Issue by alexandrutocar** [GrandSchtroumpf/qwik-hueeye#3]
Are `LiAttributes`, `DivAttributes`, etc. meant to be used internally or as helpers? They are very useful as helpers, and if the intended use was public, I would submit a PR with all the mappings.

**Comment by GrandSchtroumpf** [comment]
Hey @uceumice, sorry I don't know why I've haven't get the notification for the issue. Don't hesitate to tag me next time, I'll be more reactive.
As it's just an alias for existing type I would keep it internal for now, I tend not to make to much things public in an open-source library because it becomes too difficult to change after.

It's one line of typescript to reproduce it with a generic in your codebase: 
```typescript
import type { QwikIntrinsicElements } from "@builder.io/qwik";
export type Attr<Tag extends keyof QwikIntrinsicElements> = QwikIntrinsicElements[Tag];
```

**Comment by alexandrutocar** [comment]
Alright, then I guess the issue is resolved :)
